version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ems-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ems
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
