server.port = 8083
spring.application.name=API-GATEWAY


spring.cloud.gateway.routes[0].id=USER-SERVICE
spring.cloud.gateway.routes[0].uri=${USER_SERVICE_URL:http://localhost:5002}
spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**
spring.cloud.gateway.routes[0].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[1].id=EXPENSE-SERVICE
spring.cloud.gateway.routes[1].uri=${EXPENSE_SERVICE_URL:http://localhost:5003}
spring.cloud.gateway.routes[1].predicates[0]=Path=/expense/**
spring.cloud.gateway.routes[1].filters[0]=AuthenticationFilter


spring.cloud.gateway.routes[2].id=IDENTITY-SERVICE
spring.cloud.gateway.routes[2].uri=${IDENTITY_SERVICE_URL:http://localhost:9898}
spring.cloud.gateway.routes[2].predicates[0]=Path=/auth/**
